/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.googlecode.bootstrapx.model;


import org.apache.thrift.TEnum;

public enum OperateType implements TEnum {
  ADD(0),
  UPDATE(1),
  REMOVE(2);

  private final int value;

  private OperateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OperateType findByValue(int value) { 
    switch (value) {
      case 0:
        return ADD;
      case 1:
        return UPDATE;
      case 2:
        return REMOVE;
      default:
        return null;
    }
  }
}
